### ISSUE TITLE
An error occurred: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by DANTHEMANKING** [dmytrostriletskyi/threads-net#20]
unable to post, whenever i try to post i get this error:
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by RealWorldVesper** [comment]
I'm getting the same when trying to use threads.get_user.  For 4 or 5 runs it's working fine and generating the correct output, but then it will throw this error.  It feels like a rate limit, except there's literally only half a dozen calls and every one is a singular call for one user.

'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/Users/MyUsername/Desktop/threads/api/threadsNetAPI.py", line 65, in <module>
    printResult(orderResults(ts))
  File "/Users/MyUsername/Desktop/threads/api/threadsNetAPI.py", line 46, in orderResults
    followers = getFollowersFromUsername(t)
  File "/Users/MyUsername/Desktop/threads/api/threadsNetAPI.py", line 30, in getFollowersFromUsername
    return(getFollowers(getUser(getUserID(unm))))
  File "/Users/MyUsername/Desktop/threads/api/threadsNetAPI.py", line 10, in getUserID
    return(threads.get_user_id(username=uname))
  File "/Users/MyUsername/Library/Python/3.9/lib/python/site-packages/threads/main.py", line 139, in get_user_id
    user_id_key_value = re.search('"user_id":"(\d+)",', response.text).group()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by dmytrostriletskyi** [comment]
There is a specific thing that getting a `Threads` token is done not via normal API like GraphQL or REST, but you should request a plain HTML page. After that, you dive into HTML and parse the response — https://github.com/dmytrostriletskyi/threads-net/blob/main/threads/main.py#L83

The problem is that this HTML page sometime comes inconsistent and the regexps do not work. So when you see `NoneType` and `group` things, it means this error (inconsistent HTML).

> AttributeError: 'NoneType' object has no attribute 'group'

I will work more on making this more stable, of course. Thanks for the issue. 👍
