### ISSUE TITLE
threads api c#

### ISSUE THREAD

**Issue by anomjohn12** [dmytrostriletskyi/threads-net#40]
hello there.

how can i convert this repo to c#? Can I just get the sources of the get post requests can you help me to convert it to c#

**Comment by dmytrostriletskyi** [comment]
We use this library to send `requests` — https://pypi.org/project/requests

You can both research the documentation and play with it. After, you can open public and private APIs in this folder and try to analyze and understand how those used `requests` — https://github.com/dmytrostriletskyi/threads-net/tree/main/threads/apis

After, in C# you just pick any HTTP requests library and try to do the same because in all languages those libraries would have +- the same functionality.
